# cert-mananger.yml
---
# https://cert-manager.io/docs/installation/kubernetes/

- name: Add cert_manager helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "{{ cert_manager_repo }}"

- name: Install cert-manager
  kubernetes.core.helm:
    update_repo_cache: yes
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    chart_version : "{{ cert_manager_version }}"
    release_state: present
    values:
      installCRDs: true
    wait: yes # wait for pods to be ready